server:
  port: 8080

---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: vaos1994
    username: vaos
    url: jdbc:mysql://localhost:3306/spring
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
